---
- name: Loopback 100 Configuration
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Configure Lo100 IP
      ios_config:
        lines:
          - "ip address {{ ipaddress }} {{ subnetmask }}"
          - "ip ospf 1 area 0"
        parents: interface Loopback100
